version: "2"
services: 
  session:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    network_mode: host
  db:
    image: bitnami/mongodb:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    network_mode: host
  ui:
    build: 
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    network_mode: host
  app:
    restart: always
    build: ./SERVER
    working_dir: /app
    volumes:
      - ./SERVER:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - session
      - db
    network_mode: host
